---
- name: Install Kubernetes Dashboard in control_plane
  hosts: control_plane
  vars_files:
  - variables.yml
  - secret.yml

  tasks:
  - name: Test Connection
    ping:

  - name: Add Helm Keyring
    shell: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null

  - name: install apt-transport-https
    apt: 
      name: apt-transport-https
      state: present

  - name: Add keyring to source list
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list

  - name: Update apt packages
    become: true
    apt:
      update_cache: yes

  - name: install helm
    apt: 
      name: helm
      state: present

  - name: Test Helm
    win_shell: helm version
    register: helm_version

  - name: Helm Version 
    debug:
      msg: "{{ helm_version.stdout }}"



